const SAMPLE_WALLET_ADDRESS = "0x60f80121c31a0d46b5279700f9df786054aa5ee5";
const ETHEREUM_REQUES_ACCOUNTS_METHOD = "eth_requestAccounts";
const RARIBLE_API_URL =
  "https://api.rarible.org/v0.1/items/byOwner/?owner=ETHEREUM:";

export {
  SAMPLE_WALLET_ADDRESS,
  ETHEREUM_REQUES_ACCOUNTS_METHOD,
  RARIBLE_API_URL,
};
