const SAMPLE_WALLET_ADDRESS = "0xEBfb4E44a5F12E371aAd48ca0263a1373BAd0361";
const ETHEREUM_REQUES_ACCOUNTS_METHOD = "eth_requestAccounts";
const RARIBLE_API_URL =
  "https://api.rarible.org/v0.1/items/byOwner/?owner=ETHEREUM:";

export {
  SAMPLE_WALLET_ADDRESS,
  ETHEREUM_REQUES_ACCOUNTS_METHOD,
  RARIBLE_API_URL,
};
